GET https://ec2-dsw.onrender.com/curso/listarhttp

###

POST https://ec2-dsw.onrender.com/api/curso/nuevohttp
Content-Type: application/x-www-form-urlencoded

name=ABEL NUÑEZ CRUZ
&creditos= 6
###



PUT https://ec2-dsw.onrender.com/demo/edit
Content-Type: application/x-www-form-urlencoded

id=2
&name=Mateo IDAT
&creditos=7

###

DELETE https://ec2-dsw.onrender.com/demo/del
Content-Type: application/x-www-form-urlencoded

id=1

###



